# Please run I beg of you
#
owner: 472ethan
repo: status

sites:
  - name: Dk-Wiki Engine
    url: https://engine.cs472.endfind.me/api/ping
    expectedStatusCodes:
      - 200

status-website:
  cname: status.cs472.endfind.me
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dinky Web Status
  introTitle: >
    Backend health and everything, powered by **Upptime** and **GitHub**
  introMessage: >
    This is a sample status page which uses **real-time** data from
    my [GitHub repository](https://github.com/$OWNER/$REPO).
    No server required (besides GitHub's own server, of course)!
    [**Get your own for free**](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
